[tool.poetry]
name = "chat"
version = "0.1.0"
description = ""
authors = ["Valeriy Vasilenko <hitehnik132@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.12"
sqlalchemy = "^2.0.41"
aiohttp = "^3.12.12"
flake8 = "^7.2.0"
isort = "^6.0.1"
pre-commit = "^4.2.0"
uvicorn = {extras = ["standart"], version = "^0.34.3"}
alembic = "^1.16.1"
asyncpg = "^0.30.0"
python-dotenv = "^1.1.0"
websockets = "^15.0"
jinja2 = "^3.1.6"
pytest = "^8.4.0"
httpx = "^0.28.1"
coverage = "^7.9.0"
pytest-asyncio = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
