"""updated db

Revision ID: 3ed1ce0d7eb2
Revises: 8693708dc5fc
Create Date: 2023-11-08 17:42:54.505144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed1ce0d7eb2'
down_revision: Union[str, None] = '8693708dc5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'guests', ['guest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_column('guests', 'guest_id')
    # ### end Alembic commands ###
