"""updated db

Revision ID: 8693708dc5fc
Revises: 39e30fdf3968
Create Date: 2023-11-08 14:23:02.197422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8693708dc5fc'
down_revision: Union[str, None] = '39e30fdf3968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'room_id')
    # ### end Alembic commands ###
