"""Database update

Revision ID: ec0267017f08
Revises: ac96d8c64ea1
Create Date: 2023-12-08 17:05:57.815774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0267017f08'
down_revision: Union[str, None] = 'ac96d8c64ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guests', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_column('guests', 'room_id')
    # ### end Alembic commands ###
